import type { Kommunetype } from './kataloger/kommunetype';

export const ALLE_KOMMUNER = [
  { kode: '101', navn: 'København', type: 'hovedstad' },
  { kode: '147', navn: 'Frederiksberg', type: 'hovedstad' },
  { kode: '151', navn: 'Ballerup', type: 'hovedstad' },
  { kode: '153', navn: 'Brøndby', type: 'hovedstad' },
  { kode: '155', navn: 'Dragør', type: 'hovedstad' },
  { kode: '157', navn: 'Gentofte', type: 'hovedstad' },
  { kode: '159', navn: 'Gladsaxe', type: 'hovedstad' },
  { kode: '161', navn: 'Glostrup', type: 'hovedstad' },
  { kode: '163', navn: 'Herlev', type: 'hovedstad' },
  { kode: '165', navn: 'Albertslund', type: 'hovedstad' },
  { kode: '167', navn: 'Hvidovre', type: 'hovedstad' },
  { kode: '169', navn: 'Høje-Taastrup', type: 'hovedstad' },
  { kode: '173', navn: 'Lyngby-Taarbæk', type: 'hovedstad' },
  { kode: '175', navn: 'Rødovre', type: 'hovedstad' },
  { kode: '183', navn: 'Ishøj', type: 'hovedstad' },
  { kode: '185', navn: 'Tårnby', type: 'hovedstad' },
  { kode: '187', navn: 'Vallensbæk', type: 'hovedstad' },
  { kode: '190', navn: 'Furesø', type: 'hovedstad' },
  { kode: '201', navn: 'Allerød', type: 'hovedstad' },
  { kode: '210', navn: 'Fredensborg', type: 'oplands' },
  { kode: '217', navn: 'Helsingør', type: 'provinsby' },
  { kode: '219', navn: 'Hillerød', type: 'provinsby' },
  { kode: '223', navn: 'Hørsholm', type: 'hovedstad' },
  { kode: '230', navn: 'Rudersdal', type: 'hovedstad' },
  { kode: '240', navn: 'Egedal', type: 'hovedstad' },
  { kode: '250', navn: 'Frederikssund', type: 'oplands' },
  { kode: '253', navn: 'Greve', type: 'hovedstad' },
  { kode: '259', navn: 'Køge', type: 'provinsby' },
  { kode: '260', navn: 'Halsnæs', type: 'oplands' },
  { kode: '265', navn: 'Roskilde', type: 'provinsby' },
  { kode: '269', navn: 'Solrød', type: 'hovedstad' },
  { kode: '270', navn: 'Gribskov', type: 'oplands' },
  { kode: '306', navn: 'Odsherred', type: 'land' },
  { kode: '316', navn: 'Holbæk', type: 'oplands' },
  { kode: '320', navn: 'Faxe', type: 'oplands' },
  { kode: '326', navn: 'Kalundborg', type: 'land' },
  { kode: '329', navn: 'Ringsted', type: 'oplands' },
  { kode: '330', navn: 'Slagelse', type: 'provinsby' },
  { kode: '336', navn: 'Stevns', type: 'oplands' },
  { kode: '340', navn: 'Sorø', type: 'oplands' },
  { kode: '350', navn: 'Lejre', type: 'oplands' },
  { kode: '360', navn: 'Lolland', type: 'land' },
  { kode: '370', navn: 'Næstved', type: 'provinsby' },
  { kode: '376', navn: 'Guldborgsund', type: 'land' },
  { kode: '390', navn: 'Vordingborg', type: 'land' },
  { kode: '400', navn: 'Bornholm', type: 'land' },
  { kode: '410', navn: 'Middelfart', type: 'oplands' },
  { kode: '420', navn: 'Assens', type: 'oplands' },
  { kode: '430', navn: 'Faaborg-Midtfyn', type: 'oplands' },
  { kode: '440', navn: 'Kerteminde', type: 'oplands' },
  { kode: '450', navn: 'Nyborg', type: 'oplands' },
  { kode: '461', navn: 'Odense', type: 'storby' },
  { kode: '479', navn: 'Svendborg', type: 'land' },
  { kode: '480', navn: 'Nordfyns', type: 'oplands' },
  { kode: '482', navn: 'Langeland', type: 'land' },
  { kode: '492', navn: 'Ærø', type: 'land' },
  { kode: '510', navn: 'Haderslev', type: 'land' },
  { kode: '530', navn: 'Billund', type: 'land' },
  { kode: '540', navn: 'Sønderborg', type: 'land' },
  { kode: '550', navn: 'Tønder', type: 'land' },
  { kode: '561', navn: 'Esbjerg', type: 'provinsby' },
  { kode: '563', navn: 'Fanø', type: 'land' },
  { kode: '573', navn: 'Varde', type: 'land' },
  { kode: '575', navn: 'Vejen', type: 'oplands' },
  { kode: '580', navn: 'Aabenraa', type: 'land' },
  { kode: '607', navn: 'Fredericia', type: 'provinsby' },
  { kode: '615', navn: 'Horsens', type: 'provinsby' },
  { kode: '621', navn: 'Kolding', type: 'provinsby' },
  { kode: '630', navn: 'Vejle', type: 'provinsby' },
  { kode: '657', navn: 'Herning', type: 'provinsby' },
  { kode: '661', navn: 'Holstebro', type: 'provinsby' },
  { kode: '665', navn: 'Lemvig', type: 'land' },
  { kode: '671', navn: 'Struer', type: 'land' },
  { kode: '706', navn: 'Syddjurs', type: 'oplands' },
  { kode: '707', navn: 'Norddjurs', type: 'land' },
  { kode: '710', navn: 'Favrskov', type: 'oplands' },
  { kode: '727', navn: 'Odder', type: 'oplands' },
  { kode: '730', navn: 'Randers', type: 'provinsby' },
  { kode: '740', navn: 'Silkeborg', type: 'provinsby' },
  { kode: '741', navn: 'Samsø', type: 'land' },
  { kode: '746', navn: 'Skanderborg', type: 'oplands' },
  { kode: '751', navn: 'Aarhus', type: 'storby' },
  { kode: '756', navn: 'Ikast-Brande', type: 'oplands' },
  { kode: '760', navn: 'Ringkøbing-Skjern', type: 'land' },
  { kode: '766', navn: 'Hedensted', type: 'oplands' },
  { kode: '773', navn: 'Morsø', type: 'land' },
  { kode: '779', navn: 'Skive', type: 'land' },
  { kode: '787', navn: 'Thisted', type: 'land' },
  { kode: '791', navn: 'Viborg', type: 'provinsby' },
  { kode: '810', navn: 'Brønderslev', type: 'land' },
  { kode: '813', navn: 'Frederikshavn', type: 'land' },
  { kode: '820', navn: 'Vesthimmerlands', type: 'land' },
  { kode: '825', navn: 'Læsø', type: 'land' },
  { kode: '840', navn: 'Rebild', type: 'oplands' },
  { kode: '846', navn: 'Mariagerfjord', type: 'land' },
  { kode: '849', navn: 'Jammerbugt', type: 'land' },
  { kode: '851', navn: 'Aalborg', type: 'storby' },
  { kode: '860', navn: 'Hjørring', type: 'land' },
] as const satisfies ReadonlyArray<{ kode: string; navn: string; type: Kommunetype }>;

export type KommuneKode = typeof ALLE_KOMMUNER[number]['kode'];

export function findKommune(kode: string) {
  return ALLE_KOMMUNER.find(k => k.kode === kode);
}
